backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 15;
shadow-opacity = 0.8;
shadow-offset-x = -15;
shadow-offset-y = -15;

fading = false;

active-opacity = 100;
inactive-opacity = 0.94;

corner-radius = 5;
round-borders = 0.4;

blur-background = false;
blur-background-frame = false;

opacity-rule = [
  "67:class_g = 'i3bar'"
];
