monitor=,preferred,auto,auto

$mod = SUPER
$term = kitty
$menu = rofi -show drun
$browser = firefox

input {
  kb_layout = br
  kb_options = abnt2
  follow_mouse = 1
  touchpad {
    natural_scroll = yes
    disable_while_typing = false
  }
}

general {
  gaps_in = 4
  gaps_out = 4
  border_size = 2
  col.active_border = rgba(808076FF) rgba(02C2CCFF) 65deg
  col.inactive_border = rgba(808076FF)
  layout = dwindle
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    }
decoration {
  rounding = 1
  blur {
    enabled = yes
    size = 5
    passes = 1
  }
}

animations {
    enabled = yes

    bezier = fluentDecel, 0, 1, 0, 1
    bezier = instant, 0, 0, 0, 0

    animation = windows, 1, 2, fluentDecel, slide
    animation = windowsOut, 1, 2, fluentDecel, slide
    animation = border, 1, 1, instant
    animation = fade, 1, 2, fluentDecel
    animation = workspaces, 1, 2, fluentDecel, slidevert

    animation = specialWorkspace, 1, 2, fluentDecel, slidefadevert 15%
}

binds {
    bind = $mod, Return, exec, $term
    bind = $mod, R, exec, $menu
    bind = $mod, B, exec, $browser
    bind = $mod, Q, killactive
    bind = $mod, SHIFT_Q, exit
    bind = $mod, V, togglefloating
    bind = $mod, F, fullscreen, 0

    drag_threshold = 10
    bindm = $mod, mouse:272, movewindow
    bindc = $mod, mouse:272, togglefloating

    bind = $mod, h, movefocus, l
    bind = $mod, j, movefocus, d
    bind = $mod, k, movefocus, u
    bind = $mod, l, movefocus, r

    binde = $mod SHIFT, h, resizeactive, -20 0
    binde = $mod SHIFT, j, resizeactive, 0 20
    binde = $mod SHIFT, k, resizeactive, 0 -20
    binde = $mod SHIFT, l, resizeactive, 20 0

    bind = $mod, 1, workspace, 1
    bind = $mod, 2, workspace, 2
    bind = $mod, 3, workspace, 3

    bind = $mod SHIFT, 1, movetoworkspace, 1
    bind = $mod SHIFT, 2, movetoworkspace, 2
    bind = $mod SHIFT, 3, movetoworkspace, 3

    bind = , XF86AudioRaiseVolume, exec, amixer -q sset Master 5%+
    bind = , XF86AudioLowerVolume, exec, amixer -q sset Master 5%-
    bind = , XF86AudioMute, exec, amixer -q sset Master toggle

    bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%
    bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

    bind = , Print, exec, flameshot gui
}

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
